name: ceres
description: Ceres Development Tools
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.16.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  
  ceres_core:
    path: ../../packages/core/ceres_core
  ceres_ui:
    path: ../../packages/core/ceres_ui
  
  # Feature packages
  ceres_dashboard:
    path: ../../packages/features/ceres_dashboard
  ceres_network:
    path: ../../packages/features/ceres_network
  ceres_assets:
    path: ../../packages/features/ceres_assets
  ceres_runner:
    path: ../../packages/features/ceres_runner
  ceres_scripts:
    path: ../../packages/features/ceres_scripts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true